BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team4

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_showCupons.scss
- app/assets/stylesheets/utilities/_variables.scss
- app/views/cupons/show.html.erb
Add design for the view where the user see the cupon
- Design the view for cupons.
- Design responsive.
- What?: I added design to display coupons.
- Why?: It was made just to add the values obtained from DB.
> Design show cupons

- app/assets/stylesheets/pages/_showCupons.scss
- app/controllers/cupons_controller.rb
- app/models/cupon.rb
- app/views/cupons/new.html.erb
- app/views/cupons/show.html.erb
I implement a coupon map view because this function helps the users to find where the promotion is.
> Added coupon map view

- app/assets/config/manifest.js
- app/assets/images/menuburger.svg
- app/assets/stylesheets/pages/_main.scss
- app/javascript/navbarService.js
- app/views/share/_menu.html.erb
Finish hidden menu
Function to hide menu
> finish the hidden menu left

- app/controllers/cupons_controller.rb
- app/views/cupons/new.html.erb
- db/migrate/20230322223757_add_category_id_to_cupons.rb
- db/schema.rb
-Add category
>Add category to the form of add coupon
Categories Created
Categorires Called
> Add category to the form of add coupon

- app/assets/stylesheets/pages/_showCupons.scss
- app/views/cupons/show.html.erb
Implement the offer link in the show view if the offer has one.
> Render the offer link in the show view

- app/assets/stylesheets/pages/_categories.scss
- app/views/categories/index.html.erb
> Return Button in Category view

- app/views/cupons/_form_cupons.html.erb
- app/views/cupons/edit.html.erb
Implement the styles to the edit coupon view, as well as render the heder and the menu on the left
> Complete Styles in view of edit coupon

- app/controllers/mainpages_controller.rb
- app/views/mainpages/_content.html.erb
fixed bug with users without log in not get users on searchs. 
fixed problems for delete only one user foollowed and no drop all register.
- Fixed issues when trying to follow users without logging in.
- Fixed issue with deleting all followed user records when unfollowing a user.
- What?: Some unforeseen errors occurred.
- Why?: not all possibilities were reviewed.
If applicable, include screenshots of the results or screenshots that help to see changes
> Fixed bugs on search users followed.

- app/assets/stylesheets/pages/_main.scss
- app/views/mainpages/_content.html.erb
The user card has a new cool and minimalist design.
- Has been added a new design for the user card.
- It's has a responsive design.
> Added a nice design to the user card.

- app/assets/stylesheets/pages/_main.scss
- app/assets/stylesheets/pages/_showCupons.scss
- app/controllers/cupons_controller.rb
- app/controllers/mainpages_controller.rb
- app/views/cupons/show.html.erb
Add author of the cupon and  add button for follow it
> Feature#72 render the user who created the coupon and folow option

- app/assets/stylesheets/pages/_main.scss
Add new design cards cupon and slider
> add new design cards cupon

- app/views/mainpages/_content.html.erb
I only changed a line due to a logic failure that marked an error at the time of logout.
> Fix logout

- app/controllers/mainpages_controller.rb
- app/views/mainpages/_content.html.erb
- app/views/mainpages/index.html.erb
- app/views/share/_menu.html.erb
- The button on the left bar can now get all users.
- All users are displayed on the main page.
- What?: Show all users.
- Why?: increase interaction between users
> Show all users

- app/assets/stylesheets/pages/_main.scss
- app/controllers/mainpages_controller.rb
- app/views/mainpages/_content.html.erb
- app/views/mainpages/_home.html.erb
- The action of clicking on the user card works.
- Show coupons that belong to a specific user.
> Show user coupons, when user card is clicked.

- app/assets/stylesheets/pages/_main.scss
- app/assets/stylesheets/pages/_showCupons.scss
- app/views/mainpages/_content.html.erb
I implement a redesign of the coupon cards because is necessary to display the coupons for the users.
> redesign coupon cards added

- app/assets/stylesheets/pages/_main.scss
> Design Navbarscroll

- .gitignore
- railwayEnv.txt.example
- The configuration without important data.
- Just the structure of the variables.
Go to the next URL: https://bcdic22-ror-proyecto-final-team4-production.up.railway.app/
> config example for deploy

- app/assets/stylesheets/pages/_main.scss
- app/javascript/navbarService.js
I use styles to adjust the lateral menu in mobile view.
> Fix responsive lateral menu

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/pages/_main.scss
- app/assets/stylesheets/pages/_showCupons.scss
- app/models/cupon.rb
- app/views/cupons/show.html.erb
- New more serious, beautiful and responsive design.
- Fixed design bugs.
- What?: Change the design of the coupon details view.
- Why?: A more serious design was needed to display the coupon.
> Redesign view coupon details.

- app/assets/stylesheets/pages/_main.scss
- app/javascript/navbarService.js
- app/views/categories/_form.html.erb
- app/views/share/_menu.html.erb
Limit the number of characters to 18 when creating a category.
> Limit characters category

- app/assets/stylesheets/pages/_main.scss
- app/controllers/mainpages_controller.rb
- app/views/mainpages/_content.html.erb
- config/routes.rb
The administrator will have the option to delete the selected users.
> Admin can delete users

- app/controllers/cupons_controller.rb
- app/controllers/mainpages_controller.rb
- app/views/mainpages/_content.html.erb
- app/views/mainpages/index.html.erb
- config/initializers/pagy.rb
> Feature#114 pagination main page

- app/assets/stylesheets/pages/_main.scss
- app/controllers/cupons_controller.rb
- app/controllers/mainpages_controller.rb
- app/views/mainpages/index.html.erb
- config/initializers/pagy.rb
>Add design to navbar of the pagination
> Feature#119 design navbar of pagination

- app/views/devise/sessions/new.html.erb
- app/views/share/_menu.html.erb
- Convert logo to click.
- What?: Click over the logo return to main page.
- Why?: This helps users to return to the main view.
> Click on the logo.

- app/assets/stylesheets/pages/_users.scss
- app/assets/stylesheets/utilities/_variables.scss
> Feature#122 add scroll to login

- app/assets/stylesheets/pages/_categories.scss
- app/views/categories/new.html.erb
-add responsive view new category
> finish responsive view new category

- app/assets/stylesheets/pages/_main.scss
- app/assets/stylesheets/pages/_showCupons.scss
- app/assets/stylesheets/utilities/_mixins.scss
- app/views/mainpages/index.html.erb
- app/views/share/_header.html.erb
- Solve the problem in Devices with a resolution lower than 1024px, the header not look well.
- Header responsive is working fine at the moment.
- Make the header available to scroll.
- What?: Solve the proble with devises that have a resolution lower than 1024px, the header does not looked good.
- Why?: do a better sperience for the user.
> Responsive header bug resolved.

- app/assets/stylesheets/pages/_main.scss
- app/views/mainpages/_content.html.erb
- app/views/mainpages/_noFound.html.erb
- app/views/mainpages/index.html.erb
- Added new response messages for when no records are found. 
- Added a simple design to the response on empty cases.
> Added new answers for empty results.

- app/assets/stylesheets/pages/_main.scss
- app/assets/stylesheets/utilities/_variables.scss
- app/controllers/cupons_controller.rb
- app/models/cupon.rb
- app/models/vote.rb
- app/views/layouts/application.html.erb
- app/views/mainpages/index.html.erb
- db/migrate/20230418012415_create_votes.rb
- db/schema.rb
- db/seeds.rb
What did you implemented/Why did you implemented this:
I implemented a function to delete a coupon if it has -10 or more dislikes.
> Delete cuopons with 10 dislikes function added

- README.md
Se modifico el archivo README con la información del proyecto.
> Feature#136 update readme
